"""Candidate-generation helpers for benchmark manifests."""

from __future__ import annotations

from rcft.affine import AffineTheoryData
from rcft.candidate_schema import Candidate, CertificateStage, Character, GeneratorProvenance


def affine_target_to_skeleton_candidate(record: dict[str, object]) -> Candidate:
    """Convert an affine WZW target manifest row into a skeleton candidate.

    The resulting candidate intentionally contains only the leading coefficient for each
    sector. Full q-series coefficients should be added only when they are extracted or
    generated by a documented, tested character formula.
    """

    theory = AffineTheoryData.from_dict(record)
    source_keys = list(record.get("source_keys", [])) if isinstance(record.get("source_keys"), list) else []
    reference_key = str(source_keys[0]) if source_keys else None

    vacuum = Character(
        label="vacuum",
        h=theory.central_charge * 0,
        c=theory.central_charge,
        coefficients=(theory.central_charge * 0 + 1,),
    )
    nonvacuum = Character(
        label=str(theory.nonvacuum_representation),
        h=theory.nonvacuum_conformal_weight,
        c=theory.central_charge,
        coefficients=(theory.nonvacuum_representation_dimension,),
    )

    return Candidate(
        candidate_id=f"wzw_{str(record['key'])}",
        source="benchmark_target",
        n_characters=2,
        central_charge=theory.central_charge,
        characters=(vacuum, nonvacuum),
        q_precision=1,
        wronskian_index=0,
        certificate_stage=CertificateStage.GENERATED,
        subgroup="SL2Z",
        provenance=GeneratorProvenance(
            method="affine_wzw_formula_skeleton",
            reference_key=reference_key,
            parameters={"target_key": str(record["key"]), "level": theory.level},
        ),
        metadata={
            **theory.to_candidate_metadata(),
            "source_keys": source_keys,
            "skeleton_only": True,
            "q_series_status": "leading_terms_only",
            "notes": str(record.get("notes", "")),
        },
    )
